import { afterEach, describe, expect, it, vi } from "vitest";

import type { CitationProvider } from "~/integrations/types";

import { LIBRARY_REL_PATH, refreshLibraryBib } from "./aggregator";
import {
  registerCitationProvider,
  unregisterCitationProvider,
} from "./registry";

const writes: Array<{ projectRoot: string; relPath: string; content: string }> = [];

vi.mock("~/ipc", () => ({
  writeProjectTextFile: vi.fn(
    async (projectRoot: string, relPath: string, content: string) => {
      writes.push({ projectRoot, relPath, content });
    },
  ),
  readProjectTextFile: vi.fn(async () => {
    throw new Error("no local additions in this test");
  }),
}));

const project = {
  rootPath: "/tmp/proj",
  rootFile: "main.tex",
  format: "latex" as const,
  name: "Test",
};

function fakeProvider(id: string, bibtex: string): CitationProvider {
  return {
    id,
    category: "references",
    displayName: id,
    status: async () => "ready",
    searchLibrary: async () => [],
    fetchEntry: async () => ({ key: "", source: "" }),
    exportAllAsBibTex: async () => bibtex,
  };
}

afterEach(() => {
  writes.length = 0;
});

describe("refreshLibraryBib", () => {
  it("writes a unified library.bib to the project-scoped path", async () => {
    const cleanup = registerCitationProvider(
      fakeProvider("zotero", `@article{a, title = {From Zotero}}`),
    );

    const result = await refreshLibraryBib(project);
    cleanup();

    expect(writes).toHaveLength(1);
    expect(writes[0].projectRoot).toBe("/tmp/proj");
    expect(writes[0].relPath).toBe(LIBRARY_REL_PATH);
    expect(writes[0].content).toContain("From Zotero");
    expect(writes[0].content).toMatch(/^% Auto-generated by Typeward/);
    expect(result.providersOk).toBe(1);
    expect(result.totalKeys).toBe(1);
    expect(result.duplicates).toEqual([]);
  });

  it("dedupes keys across providers and reports them", async () => {
    const a = registerCitationProvider(
      fakeProvider("zotero", `@article{shared, title = {Z}}`),
    );
    const b = registerCitationProvider(
      fakeProvider("mendeley", `@article{shared, title = {M}}\n@article{only, title = {Only}}`),
    );

    const result = await refreshLibraryBib(project);
    a();
    b();

    expect(result.duplicates).toEqual(["shared"]);
    expect(result.totalKeys).toBe(2);
    expect(writes[0].content).toContain("title = {Z}");
    expect(writes[0].content).not.toContain("title = {M}");
    expect(writes[0].content).toContain("only");
  });

  it("isolates a failing provider — other providers still write", async () => {
    const failing: CitationProvider = {
      ...fakeProvider("broken", ""),
      exportAllAsBibTex: async () => {
        throw new Error("kaboom");
      },
    };
    const a = registerCitationProvider(failing);
    const b = registerCitationProvider(
      fakeProvider("ok", `@article{kept, title = {OK}}`),
    );

    const result = await refreshLibraryBib(project);
    a();
    b();

    expect(result.providersFailed).toBe(1);
    expect(result.providersOk).toBe(1);
    expect(writes[0].content).toContain("kept");
  });

  it("registry is idempotent on duplicate registration", async () => {
    const provider = fakeProvider("dup", `@article{x, title = {X}}`);
    registerCitationProvider(provider);
    registerCitationProvider(provider);

    const result = await refreshLibraryBib(project);
    unregisterCitationProvider(provider.id);

    expect(result.providersOk).toBe(1);
    expect(result.totalKeys).toBe(1);
  });
});
