import { describe, expect, it } from "vitest";

import { dedupeBibTex, parseBibTex } from "./bibtex";

describe("parseBibTex", () => {
  it("splits a simple entry", () => {
    const entries = parseBibTex(`@article{smith2020,
  title = {Hello},
  author = {Smith, J.},
  year = {2020}
}`);
    expect(entries).toHaveLength(1);
    expect(entries[0]).toMatchObject({ type: "article", key: "smith2020" });
    expect(entries[0].source).toContain("smith2020");
    expect(entries[0].source.endsWith("}")).toBe(true);
  });

  it("handles balanced braces inside values", () => {
    const entries = parseBibTex(`@misc{nested,
  title = {{A} {B} {C}},
}`);
    expect(entries).toHaveLength(1);
    expect(entries[0].key).toBe("nested");
    expect(entries[0].source).toContain("{A} {B} {C}");
  });

  it("ignores @string, @preamble, @comment", () => {
    const entries = parseBibTex(`@string{j = "Journal"}
@preamble{"text"}
@comment{ignored}
@article{kept2021, title = {Hi}}`);
    expect(entries.map((e) => e.key)).toEqual(["kept2021"]);
  });

  it("recovers across a malformed block", () => {
    const entries = parseBibTex(`@article{ok1, title = {Hi}}
@notvalid {nokey}
@article{ok2, title = {Bye}}`);
    expect(entries.map((e) => e.key)).toContain("ok1");
    expect(entries.map((e) => e.key)).toContain("ok2");
  });

  it("returns empty for empty input", () => {
    expect(parseBibTex("")).toEqual([]);
    expect(parseBibTex("   \n  % a comment outside any entry\n")).toEqual([]);
  });
});

describe("dedupeBibTex", () => {
  it("keeps the first occurrence and reports duplicates", () => {
    const result = dedupeBibTex([
      {
        providerId: "zotero",
        bibtex: `@article{shared, title = {From Zotero}}
@article{onlyZotero, title = {Z only}}`,
      },
      {
        providerId: "mendeley",
        bibtex: `@article{shared, title = {From Mendeley}}
@article{onlyMendeley, title = {M only}}`,
      },
    ]);

    expect(result.duplicates).toEqual(["shared"]);
    expect(result.bibtex).toContain("From Zotero");
    expect(result.bibtex).not.toContain("From Mendeley");
    expect(result.bibtex).toContain("onlyZotero");
    expect(result.bibtex).toContain("onlyMendeley");
  });

  it("prefixes a header with per-provider counts", () => {
    const result = dedupeBibTex([
      { providerId: "zotero", bibtex: `@article{a, title = {A}}` },
    ]);
    expect(result.bibtex).toMatch(/^% Auto-generated by Typeward/);
    expect(result.bibtex).toContain("zotero: 1 entries");
  });

  it("returns header-only output for empty sources", () => {
    const result = dedupeBibTex([]);
    expect(result.bibtex).toMatch(/^% Auto-generated by Typeward/);
    expect(result.duplicates).toEqual([]);
  });
});
